import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import time
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
import matplotlib.pyplot as plt
from fpdf import FPDF
import base64

# --- CONFIGURATION & BRANDING ---
st.set_page_config(page_title="Azeez Student Predictor", page_icon="🎓", layout="centered")

# Custom CSS to hide Streamlit branding and add Azeez Horizon style
hide_st_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            .stButton>button {
                background-color: #4CAF50;
                color: white;
                border-radius: 10px;
                width: 100%;
            }
            </style>
            """
st.markdown(hide_st_style, unsafe_allow_html=True)

# --- BACKEND: GOOGLE SHEETS ---
def save_to_sheet(name, phone, score):
    try:
        scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
        # Check if secrets exist (for Cloud) or handle gracefully
        if "gcp_service_account" in st.secrets:
            creds_dict = st.secrets["gcp_service_account"]
            creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
            client = gspread.authorize(creds)
            sheet = client.open("Azeez_Leads").sheet1
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            sheet.append_row([name, phone, str(score), current_time])
            return True
        else:
            st.error("Database secret not found.")
            return False
    except Exception as e:
        st.error(f"Database Error: {e}")
        return False

# --- FEATURE: PDF GENERATOR ---
def create_pdf(name, score, hours, sleep, advice):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    
    # Header
    pdf.cell(200, 10, txt="Azeez Horizon: Student Report", ln=1, align='C')
    pdf.line(10, 20, 200, 20)
    
    # Content
    pdf.set_font("Arial", size=12)
    pdf.ln(20)
    pdf.cell(200, 10, txt=f"Student Name: {name}", ln=1)
    pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%d-%b-%Y')}", ln=1)
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=f"AI Predicted Score: {score}%", ln=1)
    
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Study Hours: {hours} hrs | Sleep: {sleep} hrs", ln=1)
    pdf.ln(10)
    
    pdf.set_text_color(255, 0, 0) if score < 60 else pdf.set_text_color(0, 128, 0)
    pdf.multi_cell(0, 10, txt=f"Guidance: {advice}")
    
    # Footer
    pdf.set_y(-30)
    pdf.set_text_color(100, 100, 100)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Generated by Azeez Library & Classes AI System", 0, 0, 'C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- ML MODEL (Hidden Logic) ---
# Training Data (Hidden from user)
data = {
    'Study_Hours': [2, 4, 6, 8, 10, 3, 5, 7, 9, 12],
    'Prev_Marks': [50, 60, 75, 85, 95, 55, 70, 80, 90, 98],
    'Sleep_Hours': [9, 8, 7, 7, 8, 8, 7, 6, 8, 8],
    'Final_Score': [55, 65, 82, 88, 98, 58, 72, 85, 93, 99]
}
df = pd.DataFrame(data)
X = df[['Study_Hours', 'Prev_Marks', 'Sleep_Hours']]
y = df['Final_Score']
model = LinearRegression()
model.fit(X, y)

# --- UI LAYOUT ---
st.title("🚀 Azeez Horizon")
st.subheader("AI Performance Predictor")
st.markdown("Enter your daily habits to see your future Board Exam Score.")

col1, col2 = st.columns(2)

with col1:
    name = st.text_input("Name")
    prev = st.number_input("Last Exam %", 0, 100, 65)

with col2:
    hours = st.slider("Study Hours (Daily)", 0, 14, 4)
    sleep = st.slider("Sleep Hours", 4, 12, 7)

# --- PREDICTION LOGIC ---
if st.button("Analyze My Future 🔮"):
    if name:
        with st.spinner("Analyzing Study Patterns..."):
            time.sleep(1.5) # Suspense
            
            # Predict
            user_input = np.array([[hours, prev, sleep]])
            predicted_score = round(model.predict(user_input)[0], 1)
            if predicted_score > 100: predicted_score = 99.5
            if predicted_score < 0: predicted_score = 0
            
            # Hinglish Advice Logic
            if predicted_score >= 90:
                advice = "Excellent! You are on Topper track. Focus on solving Sample Papers now."
                color = "green"
            elif predicted_score >= 70:
                advice = "Good job! Thoda aur push karo, 90+ possible hai. consistency maintain rakho."
                color = "blue"
            else:
                advice = "Alert! You need to change your routine. Join Azeez Library for focused study."
                color = "red"

            # 1. DISPLAY RESULT
            st.markdown("---")
            st.markdown(f"<h2 style='text-align: center; color: {color};'>{predicted_score}%</h2>", unsafe_allow_html=True)
            st.info(f"💡 **Advice:** {advice}")

            # 2. VISUALIZATION (Comparison Graph)
            st.write("### 📊 Where do you stand?")
            fig, ax = plt.subplots(figsize=(6, 3))
            categories = ['Average Student', 'Topper', 'YOU']
            scores = [65, 95, predicted_score]
            colors = ['gray', 'green', color]
            
            ax.barh(categories, scores, color=colors)
            ax.set_xlim(0, 100)
            st.pyplot(fig)

            # 3. DOWNLOAD REPORT (The Pro Feature)
            pdf_bytes = create_pdf(name, predicted_score, hours, sleep, advice)
            st.download_button(
                label="📄 Download Official Report Card",
                data=pdf_bytes,
                file_name=f"{name}_Azeez_Report.pdf",
                mime="application/pdf"
            )
            
            # Store for Lead Gen
            st.session_state['score'] = predicted_score
            st.session_state['name'] = name

    else:
        st.warning("Please enter your name.")

# --- LEAD GENERATION (Bottom) ---
if 'score' in st.session_state and st.session_state['score'] < 85:
    st.markdown("---")
    st.write("### 🚀 Want to increase this score?")
    st.write("Get a **Free Counselling Session** at Azeez Classes.")
    
    with st.form("lead_form"):
        phone = st.text_input("Parent's Phone Number", placeholder="98XXXXXXXX")
        submit = st.form_submit_button("Book Free Session")
        
        if submit and len(phone) == 10:
            save_to_sheet(st.session_state['name'], phone, st.session_state['score'])
            st.success("Request Sent! We will contact you.")